# Generated by Django 4.1.5 on 2023-01-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='image',
            field=models.ImageField(default='default.png', upload_to='product_images/'),
        ),
    ]
